
export const lmpm = {
    "content" : [ {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 101441,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 16,
        "dsFilial" : "ITU - A"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 101443,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 19,
        "dsFilial" : "BROOKLIN - A"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 101444,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 39,
        "dsFilial" : "PARAISO - A"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 101445,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 60,
        "dsFilial" : "ALPHAVILLE - A"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 101452,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 81688,
        "dsProduto" : "PROFENID ENT 100MG 20S",
        "filial" : 1407,
        "dsFilial" : "DF - 307 NORTE"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100944,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 201,
        "dsFilial" : "PAMPULHA"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100945,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 230,
        "dsFilial" : "SUZANO"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100946,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 255,
        "dsFilial" : "MADUREIRA"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100947,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 260,
        "dsFilial" : "VINHEDO"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100948,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 283,
        "dsFilial" : "NITEROI - C"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100949,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 314,
        "dsFilial" : "TRES FIGUEIRAS"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100950,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 329,
        "dsFilial" : "ALDEIA DA SERRA"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100951,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 284,
        "dsFilial" : "FREGUESIA"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100952,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 308,
        "dsFilial" : "CAMPINAS - J"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100953,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 300,
        "dsFilial" : "BATATAIS"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100954,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 326,
        "dsFilial" : "ARAPONGAS"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100955,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 1546,
        "dsFilial" : "CALDAS NOVAS"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100956,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 1525,
        "dsFilial" : "CAMINHO DAS ARVORES"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100957,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 1382,
        "dsFilial" : "DF RODOVIÁRIA"
    }, {
        "nrCadastroLog" : null,
        "cdItem" : null,
        "dsAnterior" : null,
        "dsAtual" : null,
        "cdEstoqueIdeal" : 100958,
        "cdOperador" : 1,
        "nmOperador" : null,
        "dsEstoqueIdeal" : "Minimo de Demanda - LMPM",
        "dtAtualizacao" : "24/08/2020 03:00:00",
        "dtFimVigencia" : "2020-09-19",
        "dtInicioVigencia" : "2020-08-25",
        "pcVigenciaFour" : 100,
        "pcVigenciaOne" : 100,
        "pcVigenciaThree" : 100,
        "pcVigenciaTwo" : 100,
        "qtEstoque" : 10,
        "cdMotivo" : 3,
        "dsMotivo" : "LMPM",
        "cdTipo" : 2,
        "dsTipo" : "Minimo de Demanda",
        "produto" : 74063,
        "dsProduto" : "SANDRENA 0,5MG 28 ENV",
        "filial" : 1383,
        "dsFilial" : "SHOPPING IGUATEMI"
    } ],
    "pageable" : {
        "sort" : {
            "sorted" : false,
            "unsorted" : true
        },
        "pageSize" : 20,
        "pageNumber" : 0,
        "offset" : 0,
        "paged" : true,
        "unpaged" : false
    },
    "totalPages" : 92,
    "totalElements" : 1827,
    "last" : false,
    "first" : true,
    "sort" : {
        "sorted" : false,
        "unsorted" : true
    },
    "numberOfElements" : 20,
    "size" : 20,
    "number" : 0
};

export const extra = {
    "content" : [ ],
    "pageable" : {
        "sort" : {
            "sorted" : false,
            "unsorted" : true
        },
        "pageSize" : 20,
        "pageNumber" : 0,
        "offset" : 0,
        "paged" : true,
        "unpaged" : false
    },
    "totalPages" : 92,
    "totalElements" : 1827,
    "last" : false,
    "first" : true,
    "sort" : {
        "sorted" : false,
        "unsorted" : true
    },
    "numberOfElements" : 20,
    "size" : 20,
    "number" : 0
};
